<a href="https://colab.research.google.com/github/Kaini9/Data-Analytics-Training/blob/main/Pandas/Assignment/25%2B_conditional_practice_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [8]:
import pandas as pd

df = pd.read_csv("/content/titanic_dataset.csv")
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [12]:
df.loc[df["Fare"] > 50, ["Fare", "Age", "Embarked"]]

          Fare   Age Embarked
1      71.2833  38.0        C
3      53.1000  35.0        S
6      51.8625  54.0        S
27    263.0000  19.0        S
31    146.5208   NaN        C
...        ...   ...      ...
1291  164.8667  30.0        S
1293   59.4000  22.0        C
1298  211.5000  50.0        C
1302   90.0000  37.0        Q
1305  108.9000  39.0        C

[240 rows x 3 columns]

In [9]:
df.loc[df["Fare"] > 50 , ["Fare", "Age", "Embarked"]]

          Fare   Age Embarked
1      71.2833  38.0        C
3      53.1000  35.0        S
6      51.8625  54.0        S
27    263.0000  19.0        S
31    146.5208   NaN        C
...        ...   ...      ...
1291  164.8667  30.0        S
1293   59.4000  22.0        C
1298  211.5000  50.0        C
1302   90.0000  37.0        Q
1305  108.9000  39.0        C

[240 rows x 3 columns]

In [17]:
df.loc[df["Age"] < 50, ["Name","Sex"]]

                                                   Name     Sex
0                               Braund, Mr. Owen Harris    male
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                                Heikkinen, Miss. Laina  female
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                              Allen, Mr. William Henry    male
...                                                 ...     ...
1300                          Peacock, Miss. Treasteall  female
1302    Minahan, Mrs. William Edward (Lillian E Thorpe)  female
1303                     Henriksson, Miss. Jenny Lovisa  female
1305                       Oliva y Ocana, Dona. Fermina  female
1306                       Saether, Mr. Simon Sivertsen    male

[936 rows x 2 columns]

In [23]:
df.loc[df["Survived"]==1,:]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
1300,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
1301,1302,1,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1303,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

pclass 1 ma janey male haru ko naam ra fare

In [38]:
df.loc[(df["Pclass"] == 1) & (df["Sex"] == "male"), ["Fare","Name"]]

          Fare                            Name
6      51.8625         McCarthy, Mr. Timothy J
23     35.5000    Sloper, Mr. William Thompson
27    263.0000  Fortune, Mr. Charles Alexander
30     27.7208        Uruchurtu, Don. Manuel E
34     82.1708         Meyer, Mr. Edgar Joseph
...        ...                             ...
1269   50.0000     Hipkins, Mr. William Edward
1281   93.5000      Payne, Mr. Vivian Ponsonby
1294   47.1000          Carrau, Mr. Jose Pedro
1295   27.7208    Frauenthal, Mr. Isaac Gerald
1298  211.5000      Widener, Mr. George Dunton

[179 rows x 2 columns]

22 wa 22 vanda sano age ko min fare

In [70]:
df.loc[(df["Age"] > 22) & (df["Fare"] == df["Fare"].min()), ["Fare","Name"]]

      Fare                             Name
179    0.0              Leonard, Mr. Lionel
263    0.0            Harrison, Mr. William
271    0.0     Tornquist, Mr. William Henry
597    0.0              Johnson, Mr. Alfred
806    0.0           Andrews, Mr. Thomas Jr
822    0.0  Reuchlin, Jonkheer. John George
1263   0.0          Ismay, Mr. Joseph Bruce

kun class ma gako manxe dherai bachey ta

In [60]:
df.groupby("Pclass")["Survived"].sum()

Pclass
1    186
2    117
3    191
Name: Survived, dtype: int64

Which one is more common, male or female?

In [71]:
df.loc[df["Pclass"] == 1, "Sex"].value_counts()

Sex
male      179
female    144
Name: count, dtype: int64

In [52]:
df.loc[df["Age"] < 22, "Fare"].max()

263.0

In [ ]:
# syntax for loc
#df.loc[row_condition, column_selection]

In [ ]:
df[df["Age"]>30]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.loc[df["Age"] > 30, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# Passengers who survived
df.loc[df["Survived"] == 1, ["Name","Age","Survived"]]

                                                  Name   Age  Survived
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                               Heikkinen, Miss. Laina  26.0         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0         1
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0         1
..                                                 ...   ...       ...
875                   Najib, Miss. Adele Kiamie "Jane"  15.0         1
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0         1
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0         1
887                       Graham, Miss. Margaret Edith  19.0         1
889                              Behr, Mr. Karl Howell  26.0         1

[342 rows x 3 columns]

In [ ]:
df.loc[df["Survived"] == 0, ["Name","Age","Survived","Embarked"]]

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
#Passengers in 1st class
df.loc[df["Pclass"]==1,["Name","Age","Pclass","Sex"]]

                                                  Name   Age  Pclass     Sex
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1  female
6                              McCarthy, Mr. Timothy J  54.0       1    male
11                            Bonnell, Miss. Elizabeth  58.0       1  female
23                        Sloper, Mr. William Thompson  28.0       1    male
..                                                 ...   ...     ...     ...
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0       1  female
872                           Carlsson, Mr. Frans Olof  33.0       1    male
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0       1  female
887                       Graham, Miss. Margaret Edith  19.0       1  female
889                              Behr, Mr. Karl Howell  26.0       1    male

[216 rows x 4 columns]

In [ ]:
df.loc[df["Pclass"]==1,["Name","Age","Pclass","Sex"]]

In [ ]:
# Age > 30 AND Survived
df.loc[(df["Age"] > 30) & (df["Survived"] == 0), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# Age < 18 OR Female

In [ ]:
# make a 5 question  live and practice

In [ ]:
# find out the members numbers  of 3rd class who is female
df.loc[(df["Pclass"]==3) & (df["Sex"]=="female"),["Pclass","Sex","Name"]]

     Pclass     Sex                                               Name
2         3  female                             Heikkinen, Miss. Laina
8         3  female  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10        3  female                    Sandstrom, Miss. Marguerite Rut
14        3  female               Vestrom, Miss. Hulda Amanda Adolfina
18        3  female  Vander Planke, Mrs. Julius (Emelia Maria Vande...
..      ...     ...                                                ...
863       3  female                  Sage, Miss. Dorothy Edith "Dolly"
875       3  female                   Najib, Miss. Adele Kiamie "Jane"
882       3  female                       Dahlberg, Miss. Gerda Ulrika
885       3  female               Rice, Mrs. William (Margaret Norton)
888       3  female           Johnston, Miss. Catherine Helen "Carrie"

[144 rows x 3 columns]

In [ ]:
# find out the members numbers  of 3rd class who is male

In [ ]:
# Female passengers older than 25
df.loc[(df["Sex"] == "female") & (df["Age"] > 25), ["Name", "Age", "Pclass"]]

                                                  Name   Age  Pclass
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1
2                               Heikkinen, Miss. Laina  26.0       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0       3
11                            Bonnell, Miss. Elizabeth  58.0       1
..                                                 ...   ...     ...
866                       Duran y More, Miss. Asuncion  27.0       2
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0       1
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0       2
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0       1
885               Rice, Mrs. William (Margaret Norton)  39.0       3

[139 rows x 3 columns]

In [ ]:
# Female passengers older than 25

In [ ]:
# Average age of survivors
df.loc[df["Survived"]==1,"Age"].mean()

np.float64(28.343689655172415)

In [ ]:
#Rich passengers (Fare > 100) who survived only find name and age

In [ ]:
# find the name and age of Children (<15) in 3rd class

In [ ]:
# Count passengers older than 60
df.loc[df["Age"] > 60, :].shape[0]

In [ ]:
# your task take a another datasets and make a 30 to 50 question and do a practcie like this

Show all passengers who survived.

In [ ]:
df.loc[df["Survived"] == 1, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
1300,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
1301,1302,1,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1303,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

2. Show all passengers who did not survive

In [ ]:
df.loc[df["Survived"] == 0, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1308,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

3. Age greater than 30

In [ ]:
df.loc[df["Age"] > 30, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1295,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
1298,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S

4. Age less than 18

In [ ]:
df.loc[df["Age"] < 18, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
1270,1271,0,3,"Asplund, Master. Carl Edgar",male,5.0,4,2,347077,31.3875,NaN,S
1280,1281,0,3,"Palsson, Master. Paul Folke",male,6.0,3,1,349909,21.0750,NaN,S
1283,1284,0,3,"Abbott, Master. Eugene Joseph",male,13.0,0,2,C.A. 2673,20.2500,NaN,S
1294,1295,0,1,"Carrau, Mr. Jose Pedro",male,17.0,0,0,113059,47.1000,NaN,S
1300,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S

5. Fare more than 100

In [ ]:
df.loc[df["Fare"] > 100, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C
...,...,...,...,...,...,...,...,...,...,...,...,...
1262,1263,1,1,"Wilson, Miss. Helen Alice",female,31.0,0,0,16966,134.5000,E39 E41,C
1266,1267,1,1,"Bowen, Miss. Grace Scott",female,45.0,0,0,PC 17608,262.3750,NaN,C
1291,1292,1,1,"Bonnell, Miss. Caroline",female,30.0,0,0,36928,164.8667,C7,S
1298,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

6. Fare less than 20

In [ ]:
df.loc[df["Fare"] < 20, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1301,1302,1,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
1303,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S

7. Show female passengers

In [ ]:
df.loc[df["Sex"] == "female", :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
1300,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
1301,1302,1,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1303,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

8. Show Pclass 1 passengers

In [ ]:
df.loc[df["Pclass"] == 1, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1294,1295,0,1,"Carrau, Mr. Jose Pedro",male,17.0,0,0,113059,47.1000,NaN,S
1295,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
1298,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

LETS USE AND, OR

 Male AND survived

In [ ]:
df.loc[(df["Sex"] == "male") & (df["Survived"] == 1), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

Age above 30 AND survived

In [ ]:
df.loc[(df["Age"] > 30) & (df["Survived"] == 1), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1266,1267,1,1,"Bowen, Miss. Grace Scott",female,45.0,0,0,PC 17608,262.3750,NaN,C
1282,1283,1,1,"Lines, Mrs. Ernest H (Elizabeth Lindsey James)",female,51.0,0,1,PC 17592,39.4000,D28,S
1288,1289,1,1,"Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...",female,48.0,1,1,13567,79.2000,B41,C
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

Age below 18 AND survived

In [ ]:
df.loc[(df["Age"] < 18) & (df["Survived"] == 1), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
1206,1207,1,3,"Hagardon, Miss. Kate",female,17.00,0,0,AQ/3. 30631,7.7333,NaN,Q
1217,1218,1,2,"Becker, Miss. Ruth Elizabeth",female,12.00,2,1,230136,39.0000,F4,S
1236,1237,1,3,"Abelseth, Miss. Karen Marie",female,16.00,0,0,348125,7.6500,NaN,S
1245,1246,1,3,"Dean, Miss. Elizabeth Gladys Millvina""""",female,0.17,1,2,C.A. 2315,20.5750,NaN,S
1300,1301,1,3,"Peacock, Miss. Treasteall",female,3.00,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S

Fare above 100 AND survived

In [ ]:
df.loc[(df["Fare"] > 100) & (df["Survived"] == 1), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
195,196,1,1,"Lurette, Miss. Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss. Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss. Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss. Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
380,381,1,1,"Bidois, Miss. Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss. Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
537,538,1,1,"LeRoy, Miss. Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss. Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss. Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S
915,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.00,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
944,945,1,1,"Fortune, Miss. Ethel Flora",female,28.00,3,2,19950,263.0000,C23 C25 C27,S
950,951,1,1,"Chaudanson, Miss. Victorine",female,36.00,0,0,PC 17608,262.3750,B61,C
960,961,1,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.00,1,4,19950,263.0000,C23 C25 C27,S
965,966,1,1,"Geiger, Miss. Amalie",female,35.00,0,0,113503,211.5000,C130,C
1005,1006,1,1,"Straus, Mrs. Isidor (Rosalie Ida Blun)",female,63.00,1,0,PC 17483,221.7792,C55 C57,S
1032,1033,1,1,"Daniels, Miss. Sarah",female,33.00,0,0,113781,151.5500,NaN,S
1047,1048,1,1,"Bird, Miss. Ellen",female,29.00,0,0,PC 17483,221.7792,C97,S
1075,1076,1,1,"Douglas, Mrs. Frederick Charles (Mary Helene B...",female,27.00,1,1,PC 17558,247.5208,B58 B60,C
1109,1110,1,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.00,1,1,113503,211.5000,C80,C
1130,1131,1,1,"Douglas, Mrs. Walter Donald (Mahala Dutton)",female,48.00,1,0,PC 17761,106.4250,C86,C
1163,1164,1,1,"Clark, Mrs. Walter Miller (Virginia McDowell)",female,26.00,1,0,13508,136.7792,C89,C
1205,1206,1,1,"White, Mrs. John Stuart (Ella Holmes)",female,55.00,0,0,PC 17760,135.6333,C32,C
1215,1216,1,1,"Kreuchen, Miss. Emilie",female,39.00,0,0,24160,211.3375,NaN,S
1234,1235,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.00,0,1,PC 17755,512.3292,B51 B53 B55,C
1262,1263,1,1,"Wilson, Miss. Helen Alice",female,31.00,0,0,16966,134.5000,E39 E41,C
1266,1267,1,1,"Bowen, Miss. Grace Scott",female,45.00,0,0,PC 17608,262.3750,NaN,C
1291,1292,1,1,"Bonnell, Miss. Caroline",female,30.00,0,0,36928,164.8667,C7,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00,0,0,PC 17758,108.9000,C105,C

Female AND age above 30

In [ ]:
df.loc[(df["Sex"] == "female") & (df["Age"] > 30), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1266,1267,1,1,"Bowen, Miss. Grace Scott",female,45.0,0,0,PC 17608,262.3750,NaN,C
1282,1283,1,1,"Lines, Mrs. Ernest H (Elizabeth Lindsey James)",female,51.0,0,1,PC 17592,39.4000,D28,S
1288,1289,1,1,"Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...",female,48.0,1,1,13567,79.2000,B41,C
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

Male AND Pclass 1

In [ ]:
df.loc[(df["Sex"] == "male") & (df["Pclass"] == 1), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
1269,1270,0,1,"Hipkins, Mr. William Edward",male,55.0,0,0,680,50.0000,C39,S
1281,1282,0,1,"Payne, Mr. Vivian Ponsonby",male,23.0,0,0,12749,93.5000,B24,S
1294,1295,0,1,"Carrau, Mr. Jose Pedro",male,17.0,0,0,113059,47.1000,NaN,S
1295,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
1298,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C

Age above 40 AND Fare above 50

In [ ]:
df.loc[(df["Age"] > 40) & (df["Fare"] > 50), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.0,1,0,36973,83.4750,C83,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1259,1260,1,1,"Gibson, Mrs. Leonard (Pauline C Boeson)",female,45.0,0,1,112378,59.4000,NaN,C
1265,1266,1,1,"Dodge, Mrs. Washington (Ruth Vidaver)",female,54.0,1,1,33638,81.8583,A34,S
1266,1267,1,1,"Bowen, Miss. Grace Scott",female,45.0,0,0,PC 17608,262.3750,NaN,C
1288,1289,1,1,"Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...",female,48.0,1,1,13567,79.2000,B41,C
1298,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C

Age below 18 OR female

In [ ]:
df.loc[(df["Age"] < 18) | (df["Sex"] == "female"), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1300,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
1301,1302,1,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1303,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

Age above 30 OR survived

In [ ]:
df.loc[(df["Age"] > 30) | (df["Survived"] == 1), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1301,1302,1,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1303,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S

Male OR Pclass 1

In [ ]:
df.loc[(df["Sex"] == "male") | (df["Pclass"] == 1), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1308,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Age below 10 OR above 60

In [ ]:
df.loc[(df["Age"] < 10) | (df["Age"] > 60), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.00,0,0,C.A. 24579,10.5000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1198,1199,0,3,"Aks, Master. Philip Frank",male,0.83,0,1,392091,9.3500,NaN,S
1245,1246,1,3,"Dean, Miss. Elizabeth Gladys Millvina""""",female,0.17,1,2,C.A. 2315,20.5750,NaN,S
1270,1271,0,3,"Asplund, Master. Carl Edgar",male,5.00,4,2,347077,31.3875,NaN,S
1280,1281,0,3,"Palsson, Master. Paul Folke",male,6.00,3,1,349909,21.0750,NaN,S
1300,1301,1,3,"Peacock, Miss. Treasteall",female,3.00,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S

specific columns and condition

Name and Age of passengers who survived

In [ ]:
df.loc[df["Survived"] == 1, ["Name", "Age"]]

                                                   Name   Age
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                                Heikkinen, Miss. Laina  26.0
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                   Nasser, Mrs. Nicholas (Adele Achem)  14.0
...                                                 ...   ...
1300                          Peacock, Miss. Treasteall   3.0
1301                             Naughton, Miss. Hannah   NaN
1302    Minahan, Mrs. William Edward (Lillian E Thorpe)  37.0
1303                     Henriksson, Miss. Jenny Lovisa  28.0
1305                       Oliva y Ocana, Dona. Fermina  39.0

[494 rows x 2 columns]

Name, Age and Fare where Fare is above 100

In [ ]:
df.loc[df["Fare"] > 100, ["Name", "Age", "Fare"]]

                                                Name   Age      Fare
27                    Fortune, Mr. Charles Alexander  19.0  263.0000
31    Spencer, Mrs. William Augustus (Marie Eugenie)   NaN  146.5208
88                        Fortune, Miss. Mabel Helen  23.0  263.0000
118                         Baxter, Mr. Quigg Edmond  24.0  247.5208
195                             Lurette, Miss. Elise  58.0  146.5208
...                                              ...   ...       ...
1262                       Wilson, Miss. Helen Alice  31.0  134.5000
1266                        Bowen, Miss. Grace Scott  45.0  262.3750
1291                         Bonnell, Miss. Caroline  30.0  164.8667
1298                      Widener, Mr. George Dunton  50.0  211.5000
1305                    Oliva y Ocana, Dona. Fermina  39.0  108.9000

[84 rows x 3 columns]

Name, Age and Embarked of female passengers

In [ ]:
df.loc[df["Sex"] == "female", ["Name", "Age", "Embarked"]]

                                                   Name   Age Embarked
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0        C
2                                Heikkinen, Miss. Laina  26.0        S
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0        S
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0        S
9                   Nasser, Mrs. Nicholas (Adele Achem)  14.0        C
...                                                 ...   ...      ...
1300                          Peacock, Miss. Treasteall   3.0        S
1301                             Naughton, Miss. Hannah   NaN        Q
1302    Minahan, Mrs. William Edward (Lillian E Thorpe)  37.0        Q
1303                     Henriksson, Miss. Jenny Lovisa  28.0        S
1305                       Oliva y Ocana, Dona. Fermina  39.0        C

[466 rows x 3 columns]

Name, Sex and Age of male survivors

In [ ]:
df.loc[(df["Sex"] == "male") & (df["Survived"] == 1), ["Name", "Sex", "Age"]]

                                Name   Sex   Age
17      Williams, Mr. Charles Eugene  male   NaN
21             Beesley, Mr. Lawrence  male  34.0
23      Sloper, Mr. William Thompson  male  28.0
36                  Mamee, Mr. Hanna  male   NaN
55                 Woolner, Mr. Hugh  male   NaN
..                               ...   ...   ...
838                  Chip, Mr. Chang  male  32.0
839             Marechal, Mr. Pierre  male   NaN
857           Daly, Mr. Peter Denis   male  51.0
869  Johnson, Master. Harold Theodor  male   4.0
889            Behr, Mr. Karl Howell  male  26.0

[109 rows x 3 columns]

Name, Age, Fare and Pclass of female survivors with Fare above 50

In [ ]:
df.loc[(df["Sex"] == "female") & (df["Survived"] == 1) & (df["Fare"] > 50), ["Name", "Age", "Fare", "Pclass"]]

,Name,Age,Fare,Pclass
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,71.2833,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,53.1000,1
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",NaN,146.5208,1
52,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",49.0,76.7292,1
61,"Icard, Miss. Amelie",38.0,80.0000,1
...,...,...,...,...
1288,"Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...",48.0,79.2000,1
1291,"Bonnell, Miss. Caroline",30.0,164.8667,1
1293,"Gibson, Miss. Dorothy Winifred",22.0,59.4000,1
1302,"Minahan, Mrs. William Edward (Lillian E Thorpe)",37.0,90.0000,1
1305,"Oliva y Ocana, Dona. Fermina",39.0,108.9000,1