<a href="https://colab.research.google.com/github/Kaini9/Data-Analytics-Training/blob/main/Pandas/Assignment/pandas_selection_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Pandas Data Selection — `[ ]`, `.loc`, `.iloc`
* Dataset: Titanic

In this notebook we learn the 3 ways to select data from a DataFrame:

| Method | Selects by | Example |
|--------|-----------|---------|
| `df["col"]` | column name | `df["Age"]` |
| `df.loc[...]` | **labels** (names) | `df.loc[0:4, ["Name","Age"]]` |
| `df.iloc[...]` | **positions** (numbers) | `df.iloc[0:5, 0:3]` |

In [2]:
import pandas as pd

df = pd.read_csv("/content/titanic_dataset.csv")   # change the path if needed
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### 1. Selecting Columns

In [3]:
# Single column -> returns a SERIES (1 column)
df["Age"]

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
        ...
1304     NaN
1305    39.0
1306    38.5
1307     NaN
1308     NaN
Name: Age, Length: 1309, dtype: float64

In [ ]:
# List of columns -> returns a DATAFRAME (note the double brackets!)
df[["Name", "Sex", "Age"]]

### 2. `.loc` — Label-based Selection (VERY IMPORTANT)

Syntax: `df.loc[row_label, column_label]`

`.loc` uses the **index labels** and column **names**.

In [4]:
# Rows with labels 0 to 4  (loc INCLUDES the end -> 5 rows!)
df.loc[0:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
# Rows + specific columns together
df.loc[0:9, ["Name", "Age", "Sex"]]

                                                 Name   Age     Sex
0                             Braund, Mr. Owen Harris  22.0    male
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                              Heikkinen, Miss. Laina  26.0  female
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                            Allen, Mr. William Henry  35.0    male
5                                    Moran, Mr. James   NaN    male
6                             McCarthy, Mr. Timothy J  54.0    male
7                      Palsson, Master. Gosta Leonard   2.0    male
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0  female
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0  female
10                    Sandstrom, Miss. Marguerite Rut   4.0  female

In [ ]:
# One row, selected columns
df.loc[0, ["Name", "Age"]]

In [ ]:
# ALL rows, specific columns  (the ':' means 'everything')
df.loc[:, ["Survived", "Pclass", "Fare"]]

### 3. `.iloc` — Position-based Selection

Syntax: `df.iloc[row_position, column_position]`

`.iloc` uses **integer positions** (0, 1, 2, ...) — like a list.

In [ ]:
# First 5 rows  (iloc EXCLUDES the end -> positions 0,1,2,3,4)
df.iloc[0:5]

In [ ]:
# Rows AND columns by position: first 5 rows, first 3 columns
df.iloc[0:5, 0:3]

### 4. The Key Difference: `loc` vs `iloc`

| | `.loc[0:4]` | `.iloc[0:4]` |
|---|---|---|
| Selects by | label | position |
| End included? | **YES** (5 rows) | **NO** (4 rows) |

**Tip: GENERALLY USE `.loc` INSTEAD OF `.iloc`** — labels do not change when the data is
sorted or filtered, positions do.

### 5. `set_index` — Now Labels and Positions Are DIFFERENT

Until now the index labels (0,1,2,...) happened to equal the positions, so `loc` and `iloc`
looked the same. Watch what happens when we make **PassengerId** the index.

In [ ]:
df.set_index("PassengerId", inplace=True)
df.head()

In [ ]:
# Now the index labels are 1...891 (PassengerId), but positions are still 0...890

df.loc[1]       # LABEL 1  -> passenger with PassengerId = 1  (the FIRST row)

In [ ]:
df.iloc[887]    # POSITION 887 -> the 888th row (its PassengerId label is 888)

In [ ]:
# Same passenger, two ways:
print("By label   ->  df.loc[888]")
print("By position ->  df.iloc[887]")
df.loc[888].equals(df.iloc[887])

## Summary

- `df["col"]` -> one column (Series); `df[["c1","c2"]]` -> many columns (DataFrame)
- `.loc[rows, cols]` -> by **labels**, end **included**
- `.iloc[rows, cols]` -> by **positions**, end **excluded**
- After `set_index`, labels and positions become different — `.loc` follows the new index
- Prefer `.loc` in daily work

## 10 Practice Questions

*(Use the Titanic DataFrame. Q1–Q8: before `set_index`; Q9–Q10: after `set_index("PassengerId")`.)*

1. Select the `Fare` column as a Series.
2. Select the columns `Name`, `Age`, and `Survived` together in one DataFrame.
3. Select the **first 10 rows** using `.iloc`.
4. Select rows with labels **5 to 10** using `.loc`. How many rows do you get, and why?
5. Using `.loc`, select rows 0 to 4 with only the columns `Name` and `Pclass`.
6. Using `.iloc`, select the first 5 rows and the first 4 columns.
7. Using `.loc`, get the value of column `Sex` for the row with label 3.
8. Select the **last row** of the DataFrame using `.iloc` (hint: negative position).
9. After `set_index("PassengerId")`, select the passenger with **ID 100** using `.loc`.
10. Select that SAME passenger using `.iloc`. Which position number did you need, and why is it different from 100?

#1

In [6]:


df["Fare"]

0         7.2500
1        71.2833
2         7.9250
3        53.1000
4         8.0500
          ...
1304      8.0500
1305    108.9000
1306      7.2500
1307      8.0500
1308     22.3583
Name: Fare, Length: 1309, dtype: float64

#2

In [7]:
df[["Name", "Age", "Survived"]]

                                                   Name   Age  Survived
0                               Braund, Mr. Owen Harris  22.0         0
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                                Heikkinen, Miss. Laina  26.0         1
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
4                              Allen, Mr. William Henry  35.0         0
...                                                 ...   ...       ...
1304                                 Spector, Mr. Woolf   NaN         0
1305                       Oliva y Ocana, Dona. Fermina  39.0         1
1306                       Saether, Mr. Simon Sivertsen  38.5         0
1307                                Ware, Mr. Frederick   NaN         0
1308                           Peter, Master. Michael J   NaN         0

[1309 rows x 3 columns]

3

In [8]:
df.iloc[0:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

4

In [9]:
df.loc[5:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S

5

In [10]:
df.loc[0:4, ["Name", "Pclass"]]

                                                Name  Pclass
0                            Braund, Mr. Owen Harris       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2                             Heikkinen, Miss. Laina       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4                           Allen, Mr. William Henry       3

6

In [11]:
df.iloc[0:5, 0:4]

,PassengerId,Survived,Pclass,Name
0,1,0,3,"Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,3,"Allen, Mr. William Henry"

7

In [12]:
df.loc[3, "Sex"]

'female'

8

In [13]:
df.iloc[-1]

PassengerId                        1309
Survived                              0
Pclass                                3
Name           Peter, Master. Michael J
Sex                                male
Age                                 NaN
SibSp                                 1
Parch                                 1
Ticket                             2668
Fare                            22.3583
Cabin                               NaN
Embarked                              C
Name: 1308, dtype: object

9

In [14]:
df.loc[100]

PassengerId                        101
Survived                             0
Pclass                               3
Name           Petranec, Miss. Matilda
Sex                             female
Age                               28.0
SibSp                                0
Parch                                0
Ticket                          349245
Fare                            7.8958
Cabin                              NaN
Embarked                             S
Name: 100, dtype: object

10

In [15]:
df.iloc[99]

PassengerId                  100
Survived                       0
Pclass                         2
Name           Kantor, Mr. Sinai
Sex                         male
Age                         34.0
SibSp                          1
Parch                          0
Ticket                    244367
Fare                        26.0
Cabin                        NaN
Embarked                       S
Name: 99, dtype: object